<?php
	$this->headScript()->appendFile(
				'/js/ckeditor/ckeditor.js',
				'text/javascript');
?>
<script type="text/javascript">
<!--
	$(document).ready(function(){
		loadDescription();
		$('#type').change(function(){
			loadDescription();
		});
		$('#percent').change(function(){
			loadDescription();
		});
		$('#save').click(function(){
			saveDescription();
		});
	});
	
	function loadDescription(){
		var type = $('#type option:selected').val();
		var percent = $('#percent option:selected').val();
		if(type != '' && percent != '' ){
			$.post(
					'/admin/numerology/get-percent',
					{
						'type' 			: type,
						'percent'	: percent,
						},
					function(data){
							CKEDITOR.instances.description.setData(data.description);
					},'json');
		}else{
			CKEDITOR.instances.description.setData('');
		}
	}

	function saveDescription(){
		var type = $('#type option:selected').val();
		var percent = $('#percent option:selected').val(); 
		if(type != '' && percent != ''){
			$.post(
					'/admin/numerology/save-percent',
					{
						'type' 			: type,
						'percent'		: percent,
						'description'	: CKEDITOR.instances.description.getData() 
						}, 
					function(data){
						
					},'json');
		}else{
			alert('Одно из обязательных полей не выбрано');
		}
	}
//-->
</script>
<h1>Совместимость</h1>
<div>
	Типы совместимости
	<select id="type">
		<option value=""></option>
		<?php foreach($this->types as $type):?>
			<option value="<?=$type['id']?>"><?=$type['type_ru']?></option>	
		<?php endforeach;?>
	</select>
</div>
<div>
	Процент совместимости
	<select id="percent">
		<option value=""></option>
		<option value="10">0-10%</option>
		<option value="20">10%-20%</option>
		<option value="30">20%-30%</option>
		<option value="40">30%-40%</option>
		<option value="50">40%-50%</option>
		<option value="60">50%-60%</option>
		<option value="70">60%-70%</option>
		<option value="80">70%-80%</option>
		<option value="90">80%-90%</option>
		<option value="100">90%-100%</option>
	</select>
</div>
<div>
	<textarea rows="1" cols="5" name="description"></textarea>
</div>
<div style="text-align: right">
	<input type="button"value="Сохранить" id="save"/>
</div>
<script type="text/javascript">
<!--
	CKEDITOR.replace( 'description',	{
		filebrowserBrowseUrl : '/js/ckfinder/ckfinder.html',
		filebrowserImageBrowseUrl : '/js/ckfinder/ckfinder.html?type=Images',
		filebrowserFlashBrowseUrl : '/js/ckfinder/ckfinder.html?type=Flash',
		filebrowserUploadUrl : '/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
		filebrowserImageUploadUrl : '/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
		filebrowserFlashUploadUrl : '/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'
	} );
//-->
</script>
