<div class="left_block">
	<div class="rgstr">
		<div class="prem_header2">Не зарегистрированны?</div>
		<div class="text">
			Чтобы использовать все позможности Astro Taro, и
			получать больше информации, вам необходимо пройти регистрацию.
		</div>
		<a href="/user/registration"><img class="vhod2" src="/files/images/ident_reg.png" alt="" /></a>
	</div>
</div>
<div class="right_block2">
	<div class="rgstr">
		<div class="prem_header2">Уже зарегистрированны</div>
		<div class="text">Войдите в свой аккаунт.</div>
		<a id="ident-enter" style="cursor:pointer;" >
			<img  class="vhod" src="/files/images/ident_enter.png" alt="" />
		</a>
	</div>
</div>
<div class="clear"></div>
<?=$this->partial('partials/bottom-text-and-banner.phtml')?>