<?php 
	$this->headScript()->appendFile(
            '/js/scripts/article.js',
            'text/javascript'
        );
?>
<div id="tag_info">
	<div class="item_header"><?=$this->tag['tagname']?></div>
	<div class="text"><?=$this->tag['description']?></div>
	<div class="the_same">
		<div class="the_same_header">В материалах встречается:</div>
		<?=$this->AlsoTags($this->paginator,$this->tags,'news');?>
	</div>
</div>
<div id="article">
	<?php if(count($this->paginator)):?>
		<?php foreach($this->paginator as $item):?>
			<?=$this->partial('partials/news/news-anonse.phtml', array('data' => $item,'tags' => $this->newstags,'tag' => $this->tag)); ?>
		<?php endforeach;?>
		<?php echo $this->paginationControl($this->paginator, 'Sliding', 'partials/article/tag-pagination.phtml',array('requestQuery' => $this->requestQuery, 'requestQueryArray' => $this->requestQueryArray,'tag' => $this->tag,'type' => 'news')) ?>
	<?php endif;?>
</div>