<div id="article">
    <div class="sonnik_header">Что приснилось?</div>
    <div class="sonnik_search">
        <form>
            <input class="sonnik_input" placeholder="Начните набирать первые буквы слова" type="text" />
            <input class="sonnik_send" type="image" src="/files/images/sendb.png" />
        </form>
    </div>
    <div class="sonnik_header">Поиск по алфавиту</div>
    <div class="sonnik_alph">
        <?php foreach(App_DreamService::getAlphabet() as $letter): ?>
            <a href="/sonnik/letter/<?=$letter?>"><?=$letter?></a>
        <?php endforeach; ?>
    </div>
    <div class="sonnik_here"><?=$this->letter?></div>
    <div class="sonnik_list">
        <div class="list_item">
            <?php foreach($this->words['first'] as $word): ?>
                <a href="/sonnik/word/<?=$word['alias']?>"><?=$word['word']?></a>
            <?php endforeach; ?>
        </div>
        <div class="list_item">
            <?php foreach($this->words['second'] as $word): ?>
                <a href="/sonnik/word/<?=$word['alias']?>"><?=$word['word']?></a>
            <?php endforeach; ?>
        </div>
        <div class="list_item">
            <?php foreach($this->words['third'] as $word): ?>
                <a href="/sonnik/word/<?=$word['alias']?>"><?=$word['word']?></a>
            <?php endforeach; ?>
        </div>
    </div>
    <?php foreach($this->types as $type): ?>
        <div class="sonnik_item">
            <div class="item_header">
                <a href="/sonnik/type/<?=$type['alias']?>"><?=$type['name']?></a>
            </div>
            <div class="text"><?=$type['description']?></div>
            <div class="clear"></div>
        </div>
    <?php endforeach;?>
</div>