<div id="result">
	<div class="sonnik_search">
		<form>
			<input id="word-search" class="sonnik_input" name="squery" placeholder="Начните набирать первые буквы слова" type="text" value="<?=$this->searchQuery?>"/>
			<input id="word-search-button" class="sonnik_send" type="submit" value="&nbsp;&nbsp;&nbsp;&nbsp;" />
		</form>
	</div>
	<div class="sonnik_header">Поиск по алфавиту</div>
	<div class="sonnik_alph">
		<?php foreach(App_DreamService::getAlphabet() as $letter): ?>
			<a href="/sonnik/<?=$letter?>"><?=$letter?></a>
		<?php endforeach; ?>
	</div>
	<div class="res_count">Результатов поиска: <?=$this->data['total']?></div>
	<?php if(count($this->data['items'])):?>
		<?php foreach($this->data['items'] as $item):?>
		<div class="result_item">
				<div class="theme">
					Сонник
				</div>
				<div class="item_header">
					<a href="/sonnik/word/<?=$item['alias']?>">
						<?=$item['word']?>
					</a>
				</div>
				<div class="text">
				</div>
		</div>
		<?php endforeach;?>
		<?=$this->partial('search/pagination.phtml',array('curPage' => $this->curPage, 'pagination' => $this->pagination,'searchQuery' => $this->searchQuery));?>
	<?php endif;?>
</div>