<div id="article">
    <div class="sonnik_opisanie">
        <div class="item_header"><?=$this->type['name']?></div>
        <div class="text">
            <?=$this->type['description']?>
            <?php if(!empty($this->type['link']) && !empty($this->type['link-text'])):?>
            <div class="more">
                <a href="<?=$this->type['link']?>"><?=$this->type['link-text']?> →</a>
            </div>
            <?php endif;?>
        </div>
        <div class="clear"></div>
    </div>
    <div class="sonnik_header">Что приснилось?</div>
    <div class="sonnik_search">
        <form>
            <input id="word-search" class="sonnik_input" name="squery" placeholder="Начните набирать первые буквы слова" type="text" value=""/>
            <input id="word-search-button" class="sonnik_send" type="submit" value="&nbsp;&nbsp;&nbsp;&nbsp;" />
        </form>
    </div>
    <div class="sonnik_header">Поиск по алфавиту</div>
    <div class="sonnik_alph">
        <?php foreach(App_DreamService::getAlphabet() as $letter): ?>
            <a href="/sonnik/type/<?=$this->type['alias']?>/<?=$letter?>"><?=$letter?></a>
        <?php endforeach; ?>
    </div>
    <div class="sonnik_here"><?=$this->letter?></div>
    <div class="sonnik_list">
        <div class="list_item">
            <?php foreach($this->words['first'] as $word): ?>
                <a href="/sonnik/word/<?=$word['alias']?>/<?=$this->type['alias']?>"><?=$word['word']?></a>
            <?php endforeach; ?>
        </div>
        <div class="list_item">
            <?php foreach($this->words['second'] as $word): ?>
                <a href="/sonnik/word/<?=$word['alias']?>/<?=$this->type['alias']?>"><?=$word['word']?></a>
            <?php endforeach; ?>
        </div>
        <div class="list_item">
            <?php foreach($this->words['third'] as $word): ?>
                <a href="/sonnik/word/<?=$word['alias']?>/<?=$this->type['alias']?>"><?=$word['word']?></a>
            <?php endforeach; ?>
        </div>
    </div>
</div>