<?=$this->doctype();?>
<html> 
<head>
	<?php 
		$this->headTitle()->setSeparator(' - ');
		$this->headTitle('Астрологический портал');
	?>
    <?=$this->headMeta();?>
    <?=$this->headTitle();?>
    <?=$this->JQuery()->setVersion('1.8.3')->enable()->setUiVersion('1.9.2')->uiEnable();?>
    
    <?=$this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css');?>
    <script type="text/javascript" src="/js/plugins/jquery.loading.1.6.4.min.js"></script>
    <?=$this->headScript()->appendFile(
            '/js/scripts/default.js',
            'text/javascript'
        )?>
    <?= $this->headLink()
		 	->appendStylesheet(
			'/css/jquery-ui.css	');?>
</head>
<body>
<div class="main">
	<div class="header">
		<div class="pre-header">
			<?php if(null === $this->userdata):?>
			<div style="text-align:right">
				<a href="/user/registration">Регистрация</a>
				<a href="#" id="auth-link">Вход</a>
				<a href="/user/recover">Восстановление пароля</a>
			</div>
			<?php else:?>
				<div style="text-align:right">
					<?php if($this->userdata->role == 'admin'):?>
						<a href="/admin">В админку</a>
					<?php endif;?>
					<a href="/profile">Мой профиль</a>
					<a href="/user/logout">Выйти</a>
				</div>
			<?php endif;?>
		</div>
		<div class="main-header">
			<div style="padding: 35px 0 0 345px">
				<form id="search-form" action="/search" method="get" >
					<input style="width:500px;" type="text" name="query" id="search" value="<?=$this->searchQuery?>"/>
					<input type="button" id="do_search" value="OK"/>
				</form>
			</div>
		</div>
		<div class="menu">
			<?=$this->partial('partials/top-menu.phtml')?>
		</div>
		<div class="breadcrumbs">
			<?= $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(false)->setSeparator(" / "); ?>
			<?php if($this->controllerName == 'divination'):?>
				<?=$this->partial('partials/divination-menu.phtml',array('divType' => $this->divType))?>
			<?php endif;?>
			<?php if($this->controllerName == 'horoscope'):?>
				<?=$this->partial('partials/horoscope/menu.phtml',array('curSign' => $this->curSign,'signs' => $this->signs))?>
			<?php endif;?>
			<?php if($this->controllerName == 'numerology'):?>
				<?=$this->partial('partials/numerology/menu.phtml',array('curType' => $this->curType))?>
			<?php endif;?>
		</div>
		<div class="page-header">
			<?=$this->pageTitle;?>
		</div>
	</div>
	<?php if($this->controllerName == 'divination' && $this->actionName == 'divination'):?>
		<?php if($this->divination['type'] == 'taro' || $this->divination['type'] == 'classic' || $this->divination['type'] == 'rune'):?>
			<?=$this->partial('partials/divination/divination-block.phtml',
								array(
										'divination' => $this->divination,
										'decks' => $this->decks,
										'divinationNet' => $this->divinationNet));?>
		<?php elseif($this->divination['type'] == 'book'):?>
			<?=$this->partial('partials/divination/divination-book.phtml',
									array(
											'divination' => $this->divination,
											'decks' => $this->decks,
											'divinationNet' => $this->divinationNet));?>
		<?php elseif($this->divination['type'] == 'other'):?>
			<?=$this->partial('partials/divination/divination-other.phtml',
									array(
											'divination' => $this->divination,
									));?>									
			<?php endif;?>																
	<?php endif;?>
	<div class="content">
		<?php if($this->controllerName != 'profile' ):?>
		<div class="left-column">
			<?php if(isset($this->categories)):?>
			<?=$this->partial('partials/leftmenu.phtml',array('categories' => $this->categories))?>
			<?php endif;?>
		</div>
		
		<div class="main-content">
			<div class="content-header">
				
			</div>
			<h1><?php echo $this->escape($this->title); ?></h1>
    		<?php echo $this->layout()->content; ?>
		</div>
		<div class="right-column">
			<?php if(isset($this->tags) && $this->controllerName == 'article'):?>
			<h3>Популярные теги</h3>
			<div><?=$this->RandomTags($this->tags)?></div>
			<?php endif;?>
			<?php if($this->controllerName == 'horoscope' && $this->type != 'list'):?>
				<h3>Гороскопы знака <?=$this->data['sign']['sign_ru']?></h3>
				<ul>
					<?php foreach($this->horoscopeTypes as $type => $text):?>
						<li>
							<?php if($type == $this->type):?>
								<?=$text?>
							<?php else:?>
								<a href="/horoscope/<?=$this->curSign?>/<?=$type?>"><?=$text?></a>
							<?php endif;?>
						</li>
					<?php endforeach;?>
				</ul>
			<?php endif;?>
			<?php if($this->controllerName == 'numerology' && $this->smallType != 'no-smalltype'):?>
				<ul>
					<?php if(isset($this->curType)):?>
					<?php foreach($this->fullTypes[$this->curType]['children'] as $key => $child):?>
						<li>
						<?php if($key == $this->smallType):?>
							<?=$child?>
						<?php else:?>
							<a href="/numerology/<?=$this->curType?>/<?=$key?>"><?=$child?></a>
						<?php endif;?>
						</li>
					<?php endforeach;?>
					<?php endif;?>
				</ul>
			<?php endif;?>
		</div>
		<?php else:?>
			<?php echo $this->layout()->content; ?>
		<?php endif;?>
		
	</div>
	<div class="footer">
	</div>
</div>
<?php if(null === $this->userdata):?>
<div id="auth" style="display:none;">
	<form action="" id="auth-form">
		<table>
			<tr>
				<td>
					<ul class="errors">
					</ul>
				</td>
			</tr>
			<tr>
				<td>
					Email
				</td>
				<td>
					<input type="text" id="email" name="email" value="" />
				</td>
			</tr>
			<tr>
				<td>
					Пароль
				</td>
				<td>
					<input type="password" id="pass" name="pass" value=""/>
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<input type="submit" id="auth-submit" value="Отправить"/> 
				</td>
			</tr>
		</table>
	</form>
</div>
<?php endif;?>
</body>
</html>