<form id="full" action="<?=$this->escape($this->element->getAction());?>" 
		method="<?=$this->escape($this->element->getMethod()); ?>"
		enctype="<?=$this->element->getEncType(); ?>">
	<span>Адрес эл. почты<img src="/files/images/must.png" alt=""></span><br />
	<?=$this->element->email;?>
	<span>Придумайте пароль<img src="/files/images/must.png" alt=""></span><br />
	<?=$this->element->pass;?>
	<span>Подтвердите пароль<img src="/files/images/must.png" alt=""></span><br />
	<?=$this->element->pass_confirm;?>
	<div class="reg_full">
		<span>Зачем мне вводить личные данные?</span><br />
		<div class="text">Составить нумерологический прогноз невозможно без Ф.И.О. и полной даты рождения. Если вы не планируете использовать данный раздел сайта, вернитесь к <a href="/user/registration">простой форме регистрации</a></div>
		<span>Как вас зовут<img src="/files/images/must.png" alt=""></span><br />
		<div class="form_left_fix" id="form_left_fix">
			<?=$this->element->fname?>
		</div>
		<div class="form_left_fix">
			<?=$this->element->lname?>
		</div>
		<?=$this->element->mname?>
		<div class="vipadalki" id="tuda_suda">
			<span>Дата рождения<img src="/files/images/must.png" alt=""></span><br />
			<?=$this->element->byear?>
			<?=$this->element->bmonth?>
			<?=$this->element->bday?>
			<div class="clear"></div><br />
			<div class="nujtak">
				<span>Пол<img src="/files/images/must.png" alt=""></span><br />
				<?=$this->element->gender;?>
			</div>
		</div>
	</div>
	<div class="captcha">
		<span>Докажите, что вы не робот<img src="/files/images/must.png" alt=""></span><br />
		<div class="captcha_content">
			<?=$this->element->full_captcha?>
		</div>
	</div>
	<div class="check_left">
		<label><?=$this->element->agree_full?><span>Я принимаю <a href="/statyi/content/17-no-tag/23-usloviya-ispolzovaniya" target="_blank">Условия использования</a> и соглашаюсь с <a href="/statyi/content/17-no-tag/24-politika-konfidentsialnosti" target="_blank">политикой конфиденциальности</a> Astro Tarot</span></label>
	</div>
	<input class="enter_send" id="full-submit" type="image" src="/files/images/reg_send.png" />
	<?=$this->element->formtype;?>
	<div class="clear"></div>
</form>