<script type="text/javascript">
<!--
function confirmation(id){
	if(confirm('Вы действительно хотите удалить этот баннер?')){
		window.location.href="/admin/banner/delete-ad/id/" + id;
	}
}
//-->
</script>
<h1>Управление рекламными баннерами</h1>
<table>
	<tr>
		<td>
			<div style="text-align:left;"><a href="/admin/banner/add-ad">Добавить баннер.</a></div>
		</td>
	</tr>
</table>
<table class="admin-table" id="article-table" style="width:950px;margin-left: 30px;">
	<tr>
		<th style="width:10%">
			Тип
		</th>
		<th style="width:10%">
			Карт.
		</th>
		<th style="width:20%">
			Линк
		</th>
		<th style="width:20%">
			Отображается в:
		</th>
		<th style="width:10%">
			Баннер
		</th>
		<th style="width:10%">
			Сквозной
		</th>
		<th style="width:20%">
			Действия
		</th>
	</tr>
	<?php if(count($this->paginator)):?>
	<?php foreach($this->paginator as $item):?>
	<tr>
		<td>
			<?=($item['outer_type'] == 'order')?'Заказной':'Партнерка'?>
		</td>
		<td>
			<?=($item['filename'] !== null)?'<img src="/files/ad/'.$item['filename'].'"/>':''?>
		</td>
		<td>
			<?=$item['link']?>
		</td>
		<td>
			<?php if($item['through'] == 'y'):?>
				-
			<?php else:?>
				<?php
					if(count($this->savedPositions)){
						foreach($this->savedPositions as $position){
							if($item['id'] == $position['banner_id']){
								foreach($this->etalonPositions as $etalon){
									if($etalon['value'] == $position['position']){
										echo $etalon['label'].';';
										break; 
									}
								}
							}
						}
					}
				?>
			<?php endif;?>
		</td>
		<td>
			<?=App_UtilsService::bannerToRu($item['banner'])?>
		</td>
		<td>
			<?=($item['through'] == 'y')?'Да':'Нет'?>
		</td>
		<td>
			<a href="/admin/banner/edit-ad/id/<?=$item['id']?>">Редактировать</a> / 
			<a style="cursor:pointer;" onclick="confirmation('<?=$item['id']?>')">Удалить</a>
		</td>
	</tr>
	<?php endforeach;?>
	<tr>
		<td colspan="2">
			<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml',array('requestQuery' => $this->requestQuery, 'requestQueryArray' => $this->requestQueryArray, 'funcName' => 'changeAgentListPage')) ?>
		</td>
	</tr>
	<?php endif;?>
</table>