<?php if(isset($this->item['theme_name'])):?>
<div class="all_divi_item">
	<img src="/files/paythemes/<?=$this->item['image']?>" alt="" />
	<div class="all_divi_item_content" style="min-height:184px;">
		<div class="item_header">
			<a href="/service/<?=$this->serviceType?>/<?=$this->item['theme_smalltype']?>"><?=$this->item['theme_name']?></a>
		</div>
		<div class="text">
			<?=iconv('windows-1251','utf-8',substr(iconv('utf-8','windows-1251',preg_replace('/<\/?[^>]+>/ims','',$this->item['description'])), 0,160));?> ... 
		</div>
		<div class="talk_like">
			<span style="color:#ff6601">Стоимость: <span style="font-size:17px;"><?=$this->item['cost']?></span></span> 
			<a href="/service/<?=$this->serviceType?>/<?=$this->item['theme_smalltype']?>">заказать →</a>
		</div>
		<div class="clear"></div>
	</div>
</div>
<?php endif;?>