					
					<div class="left_block">
						<div>
							<?php if(isset($this->comments['left']) && count($this->comments['left'])):?>
								<?php foreach($this->comments['left'] as $comment):?>
									<div id="comm_<?=$comment['id']?>" class="comment_item">
		                                <?php if(empty($comment['avatar'])):?>
											<img src="/files/images/comment_profile.png" alt="" />
										<?php else:?>
											<img src="/files/avatar/<?=$comment['avatar']?>" style="width:41px" alt="" />
										<?php endif;?>
		                                <div class="comment_content">
		                                    <div class="comment_header">
		                                    	<?=$comment['name']?>
		                                    	<span>
		                                    		<?php 
														$date = new Zend_Date(date('Y-m-d',strtotime($comment['date_created'])));
														if(date('Y-m-d') == date('Y-m-d',strtotime($comment['date_created']))){
															echo 'Сегодня&nbsp;в&nbsp;'.date('H:i',strtotime($comment['date_created']));
														}else{
															echo $date->toString(Zend_Date::DATE_LONG).'&nbsp;'.date('H:i',strtotime($comment['date_created']));
														}
													?>
		                                    	</span>
		                                    </div>
		                                    <div class="comment_text">
		                                    	<?=$comment['body']?>
		                                    </div>
		                                    <div class="dialog_line">
		                                        <a class="answer" onclick="payservice_answer('<?=$comment['name']?>')" href="javascript:void(0)">ответить</a>
		                                        <?php if(isset($this->userdata) && !empty($this->userdata)):?> 
													<a href="javascript:void(0)" onclick="abuseComment('<?=$comment['id']?>',$(this).position())">пожаловаться</a>
													<a href="javascript:void(0)" onclick="sendSpam('<?=$comment['id']?>')">это спам</a>
												<?php endif;?>
		                                        <div class="clear"></div>
		                                    </div>
		                                </div>
		                                <div id="abuse-inform_<?=$comment['id']?>" class="abuse-inform">Спасибо за участие, мы получили ваше сообщение</div>
		                            </div>
								<?php endforeach;?>
							<?php endif;?>
                        </div>
                    </div>
                    <div class="right_block">
                        <div>
                            <?php if(isset($this->comments['right']) && count($this->comments['right'])):?>
							<?php foreach($this->comments['right'] as $comment):?>
								<div id="comm_<?=$comment['id']?>" class="comment_item">
	                                <?php if(empty($comment['avatar'])):?>
										<img src="/files/images/comment_profile.png" alt="" />
									<?php else:?>
										<img src="/files/avatar/<?=$comment['avatar']?>" style="width:41px" alt="" />
									<?php endif;?>
	                                <div class="comment_content">
	                                    <div class="comment_header">
	                                    	<?=$comment['name']?>
	                                    	<span>
	                                    		<?php 
													$date = new Zend_Date($comment['date_created']);
													if(date('Y-m-d') == date('Y-m-d',strtotime($comment['date_created']))){
														echo 'Сегодня&nbsp;в&nbsp;'.date('H:i',strtotime($comment['date_created']));
													}else{
														echo $date->toString(Zend_Date::DATE_LONG).'&nbsp;'.date('H:i',strtotime($comment['date_created']));
													}
												?>
	                                    	</span>
	                                    </div>
	                                    <div class="comment_text">
	                                    	<?=$comment['body']?>
	                                    </div>
	                                    <div class="dialog_line">
	                                        <a class="answer" onclick="payservice_answer('<?=$comment['name']?>')" href="javascript:void(0)">ответить</a>
	                                        <?php if(isset($this->userdata) && !empty($this->userdata)):?> 
												<a href="javascript:void(0)" onclick="abuseComment('<?=$comment['id']?>',$(this).position())">пожаловаться</a>
												<a href="javascript:void(0)" onclick="sendSpam('<?=$comment['id']?>')">это спам</a>
											<?php endif;?>
	                                        <div class="clear"></div>
	                                    </div>
	                                </div>
	                                <div id="abuse-inform_<?=$comment['id']?>" class="abuse-inform">Спасибо за участие, мы получили ваше сообщение</div>
	                            </div>
							<?php endforeach;?>
						<?php endif;?>
                        </div>
                    </div>
                    <div class="clear"></div>
                    <div id="abuse-comment-form">
					    <div class="reference">
					         <form >
								  <table>
								  	<tr>
								  		<td>
								  			<textarea id="abuse-field" rows="3" cols="29"></textarea>
								  			<input type="hidden" id="comment" />
								  		</td>
								  	</tr>
								  	<tr>
								  		<td>
								  			<table>
								  				<tr>
								  					<td>
								  						<div class="button" style="position:static">
															<div class="button_left"></div>
															<div class="button_content">
																<a href="javascript:void(0)" onclick="sendAbuse()">Оставить жалобу</a></div>
															<div class="button_right"></div>
														</div>
								  					</td>
								  					<td>
											  			<div class="button" style="position:static">
															<div class="button_left"></div>
															<div class="button_content">
																<a href="javascript:void(0)" onclick="closeAbuse()">Отмена</a></div>
															<div class="button_right"></div>
														</div>
											  		</td>
								  				</tr>
								  			</table>
								  		</td>
								  	</tr>
								  </table>
					        </form>
					    </div>
					</div>