<img alt="" src="/files/decks/<?=$this->deck;?>/<?=$this->item['image']?>" class="tolk_rune_img">
<div class="tolk_content">
	<div class="item_header">Гексаграмма <?=$this->item['order']?>. <?=$this->item['title']?></div>
	<div class="text">
		<?=$this->item['description'];?>
	</div>
	<div id="hex_order" style="display:none;"><?=$this->item['order']?></div>
	<div id="hex_name" style="display:none;"><?=$this->item['title']?></div>
</div>
