<div id="opisanie">
	<div class="item_header">Гадания на картах Таро</div>
	<div class="text">
		<?=$this->data['root-category']['description']?> 
		<div class="more">
			<a href="/statyi/content/26-gadaniya/28-kartyi-taro">Что такое карты Таро →</a>
		</div>
	</div>
	<div class="clear"></div>
</div>
<div id="all_horo">
	<?php if($this->data):?>
		<?php foreach ($this->data as $index => $item):?>
				<?=$this->partial('partials/divination/taro-list-item.phtml',array('item' => $item))?>
		<?php endforeach;?>
<?php endif;?>
</div>