<script type="text/javascript">
<!--
$(document).ready(function(){
	$('#seacrh-button').click(function(){
		$.post('/admin/magictag/search',
				{'query':$('#query').val()},
				function(data){
					$('#tags-table').html(data);
				}
			);
	});
});
function confirmation(id,page){
	if(confirm('Вы действительно хотите удалить этот тег?')){
		window.location.href="/admin/magictag/remove/id/" + id + '/page/' + page;
	}
}
//-->
</script>
	<h1>Управление тегами магии.</h1>
	<table>
		<tr>
			<td>
				<div style="text-align:left;"><a href="/admin/magictag/add">Добавить тег.</a></div>
			</td>
			<td>
				<input id="query" type="text"/><input id="seacrh-button" type="button" value="Найти тег"/>
				<input type="button" id="clear-search" value="Очистить поиск" onclick='window.location.href="/admin/magictag"'/>
			</td>
		</tr>
	</table>
	<table class="admin-table" id="tags-table" style="width: 500px;margin-left: 30px;">
		<tr>
			<th style="width:80%">
				Тег
			</th>
			<th style="width:20%">
				Действия
			</th>
		</tr>
		<?php if(count($this->paginator)):?>
		<?php foreach($this->paginator as $item):?>
		<tr>
			<td>
				<?=$item['tagname'];?>
			</td>
			<td>
				<a href="/admin/magictag/edit/id/<?=$item['id']?><?=(!empty($this->page)?'/page/'.$this->page:'');?>">Редактировать</a> / 
				<a style="cursor:pointer;" onclick="confirmation('<?=$item['id']?>','<?=(!empty($this->page)?$this->page: (''))?>')">Удалить</a>
			</td>
		</tr>
		<?php endforeach;?>
		<tr>
			<td colspan="2">
				<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml',array('requestQuery' => $this->requestQuery, 'requestQueryArray' => $this->requestQueryArray, 'funcName' => 'changeAgentListPage')) ?>
			</td>
		</tr>
		<?php endif;?>
	</table>