<style type="text/css">
	td {
	 font-size: 16px;
	}
</style>
<table width="100%" border="0" cellspacing="0" align="center" bgcolor="#FFFFFF" >
	<tr>
		<td bgcolor="#f4f5f7" height="62" style="color: #ff8800; font-size: 32px; text-align: center;"><span style="text-align: center">Astro Tarot</span></td>
	</tr>
	<tr>
		<td height="10">&nbsp;</td>
	</tr>
	<tr>
		<td>
			<?php if($this->orderType == 'horoscope'):?>
				Заказ индивидуального гороскопа "<?=$this->orderDetailName?>"
			<?php else:?>
				Заказ индивидуального гадания "<?=$this->orderDetailName?>"
			<?php endif;?>
		</td>
	</tr>
	<tr>
		<td bgcolor="#ff8800" height="1">
		</td>
	</tr>
	<tr>
		<td >
			&nbsp;
		</td>
	</tr>
	<tr>
	    <td>
			<p>Уважаемый <?=$this->name?></p>
			<p>Ваш заказ успешно принят и отправлен в обработку. Мы отправим ответ на указанный вами адрес e-mail (<?=$this->email?>) в течении суток с момента получения оплаты.</p>
			<p><?=$this->details?></p>
	    	<p>&nbsp;</p>
	    </td>
	</tr>
	<tr>
    	<td>&nbsp;</td>
	</tr>
	<tr>
		<td bgcolor="#f4f5f7" align="right" height="40" style="color:#ff8800">Итого к оплате: <?=$this->price?>  &nbsp; &nbsp;</td>
	</tr>	
	<tr>
		<td align="right" height="50">С уважением администрация сайта <a href="http://astrotarot.ru">www.astrotarot.ru</a> &nbsp; &nbsp;</td>
	</tr>
</table>
