<style type="text/css">
	td {
	 font-size: 16px;
	}
</style>
<table width="100%" border="0" cellspacing="0" align="center" bgcolor="#FFFFFF" >
	<tr>
		<td bgcolor="#f4f5f7" height="62" style="color: #ff8800; font-size: 32px; text-align: center;"><span style="text-align: center">Astro Tarot</span></td>
	</tr>
	<tr>
		<td height="10">&nbsp;</td>
	</tr>
	<tr>
		<td>
			Смена пароля на сайте
		</td>
	</tr>
	<tr>
		<td bgcolor="#ff8800" height="1">
		</td>
	</tr>
	<tr>
		<td >
			&nbsp;
		</td>
	</tr>
	<tr>
	    <td>
			<p>Уважаемый пользователь!</p>
			<p>Ваш логин: <?=$this->login?></p>
			<p>Ваш новый пароль: <?=$this->password?></p>
	    	<p>&nbsp;</p>
	    </td>
	</tr>
	<tr>
    	<td>&nbsp;</td>
	</tr>
	<tr>
		<td align="right" height="50">С уважением администрация сайта <a href="http://astrotarot.ru">www.astrotarot.ru</a> &nbsp; &nbsp;</td>
	</tr>
</table>
