<ul id="menuV">
	<li class="root-item"><a href="/admin">Главная</a></li>
	<li class="root-item"><a href="/admin/pages">Страницы</a></li>
	<li class="root-item"><a href="/admin/poll">Голосования</a></li>
	<li class="root-item">
		<a href="#">Гадания</a>
		<ul class="nesting1">
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/divination/deck">Колоды</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/category">Категории гаданий</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/category/image">Картинки для категорий</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/divination/taro">Гадания (Таро, Классика, Руны, Книга перемен)</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
		</ul>
	</li>
	<li class="root-item">
		<a href="#">Гороскоп</a>
		<ul class="nesting1">
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/horoscope/simple">Обычное описание знаков</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/horoscope/by-time">Гороскопы по времени(неделя, месяц, год)</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/horoscope/today">Редактирование гороскопов на сегодня</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/horoscope/by-type">Гороскопы по типу(профессия, здоровье, ребенок, бизнес)</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/horoscope/by-compability">Гороскопы совместимости</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/horoscope/by-karma">Кармический гороскоп</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/horoscope/list-pages">SEO настройки и миниописания гороскопов</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
		</ul>
	</li>
	<li class="root-item">
		<a href="#">Статьи</a>
		<ul class="nesting1">
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/tag">Теги</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/article">Статьи</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
		</ul>
	</li>
	<li class="root-item">
		<a href="#">Новости</a>
		<ul class="nesting1">
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/news">Новости</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/newstag">Теги</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
		</ul>
	</li>
	<li class="root-item">
		<a href="#">Магия</a>
		<ul class="nesting1">
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/magic">Магия</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/magictag">Теги</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
		</ul>
	</li>
	<li class="root-item">
		<a href="#">Нумерология</a>
		<ul class="nesting1">
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/numerology/personal">Нумерология (персональные числа)</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/numerology/compability">Нумерология (совместимость)</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/numerology/percent">Нумерология (процент совместимости)</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
		</ul>
	</li>
	<li class="root-item">
		<a href="#">Лунный календарь</a>
		<ul class="nesting1">
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/moon">Лунные дни</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/moon/day-attributes">Атрибуты лунного дня</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/moon/moon-in-sign">Луна в знаке зодиака</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/moon/associate">Привязка лунного дня к числу месяца</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/moon/sign-associate">Привязка луны в знаке к числу месяца</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/moon/phase">Лунные фазы</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
		</ul>
	</li>
	<li class="root-item"><a href="/admin/users">Пользователи</a></li>
	<li class="root-item"><a href="/admin/comments">Комментарии</a></li>
	<li class="root-item">
		<a href="#">Баннеры</a>
		<ul class="nesting1">
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/banner/ad">Реклама</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/banner/slider">Внутренние</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
		</ul>
	</li>
	<li class="root-item">
		<a href="#">Платный сервис</a>
		<ul class="nesting1">
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/payservice/themes">Темы платного сервиса</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/payservice/gates">Платежные системы</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/payservice/edit-email">Почта для заказов</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
		</ul>
	</li>

	<li class="root-item">
		<a href="#">Сонник</a>
		<ul class="nesting1">
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/dream/word-list">Слова</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/dream/type-list">Сонники</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
			<li>
				<div class="MenuTop"></div>
				<table class="MenuLink" cellspacing="0" cellpadding="0" border="0">
					<tr>
						<td class="MenuLeft"></td>
						<td class="MenuCenter">
							<a href="/admin/dream/word-description">Описание к словам</a>
						</td>
						<td class="MenuRight"></td>
					</tr>
				</table>
				<div class="MenuBottom"></div>
			</li>
		</ul>
	</li>
</ul>