<?php if (($this->pageCount) > 1){?>
<form action="" method="get">

<?php if (is_array($this->requestQueryArray)&&count($this->requestQueryArray)) : ?>
<?php foreach ($this->requestQueryArray as $name => $val) :?>
<?php if ($name != 'items_per_page'):?>
<input type="hidden" name="<?php echo $name?>" value="<?php echo $val?>" />
<?php endif;?>
<?php endforeach;?>
<?php endif; ?>
</form>
<div style="float: right;">
	<ul class="pager">
<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <li><a href="<?= $this->url(array('page' => $this->first), null, false).$this->requestQuery; ?>">&lt;&lt;</a></li>
<?php else: ?>
  <li><a href="#">&lt;&lt;</a></li>
<?php endif; ?>
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <li><a href="<?= $this->url(array('page' => $this->previous), null, false).$this->requestQuery; ?>">&lt;</a></li>
<?php else: ?>
  <li><a href="#">&lt;</a></li>
<?php endif; ?>
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
	 <li><a href="<?= $this->url(array('page' => $page), null, false).$this->requestQuery; ?>"><?= $page; ?></a></li>
  <?php else: ?>
     <li><a href="#" class="selected"><?= $page; ?></a></li>
  <?php endif; ?>
<?php endforeach; ?>
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <li><a href="<?= $this->url(array('page' => $this->next), null, false).$this->requestQuery; ?>">&gt;</a></li>
<?php else: ?>
  <li><a href="#">&gt;</a></li>
<?php endif; ?>
<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <li><a href="<?= $this->url(array('page' => $this->last), null, false).$this->requestQuery; ?>">&gt;&gt;</a></li>
<?php else: ?>
  <li><a href="#">&gt;&gt;</a></li>
<?php endif; ?>
	</ul>
</div>
<div style="clear: both;"></div>
<?php } ?>