<div class="num_block">
	<div class="item_header" style="margin-left:0;">Важные годы жизни <?=implode(',',$this->data['anumbers'])?> лет
	</div>
	<div class="clear"></div>
</div>
<div class="num_text_block">
	<div class="text">
		<?=$this->data['description']?>
		<div class="num_more"><a onclick="showForm()" style="cursor:pointer">Произвести другой нумерологический рассчет →</a></div>
		<div class="clear"></div>
	</div>
</div>