<h2>Числа жизненного пути <?=$this->data['lifepath']['number1']?> и <?=$this->data['lifepath']['number2']?></h2>
<div>
	<?=$this->data['lifepath']['description']?>
</div>
<h2>Числа самовыражения <?=$this->data['selfexpression']['number1']?> и <?=$this->data['selfexpression']['number2']?></h2>
<div>
	<?=$this->data['selfexpression']['description']?>
</div>
<h2>Числа личности <?=$this->data['identity']['number1']?> и <?=$this->data['identity']['number2']?> </h2>
<div>
	<?=$this->data['identity']['description']?>
</div>
<h2>Числа души <?=$this->data['soul']['number1']?> и <?=$this->data['soul']['number2']?></h2>
<div>
	<?=$this->data['soul']['description']?>
</div>