<h2>Числа достижений </h2>
<div>
	<h3>Первое число достижений <?=$this->data[0]['number']?></h3>
	<?=$this->data[0]['description']?>
</div>
<div>
	<h3>Второе число достижений <?=$this->data[1]['number']?></h3>
	<?=$this->data[1]['description']?>
</div>
<div>
	<h3>Третье число достижений <?=$this->data[2]['number']?></h3>
	<?=$this->data[2]['description']?>
</div>
<div>
	<h3>Четвертое число достижений <?=$this->data[3]['number']?></h3>
	<?=$this->data[3]['description']?>
</div>