<div class="num_block">
	<img src="/files/images/profile/number/<?=$this->data[0]['number'].'.png';?>" alt="" />
	<div class="item_header">Первое число достижений <?=$this->data[0]['number_text']?></div>
	<div class="clear"></div>
</div>
<div class="num_text_block">
	<div class="item_header">Трактование числа достижений <?=$this->data[0]['number_text']?></div>
	<div class="text">
		<?=$this->data[0]['description']?>
		<div class="clear"></div>
	</div>
</div>
<div class="num_block">
	<img src="/files/images/profile/number/<?=$this->data[1]['number'].'.png';?>" alt="" />
	<div class="item_header">Второе число достижений <?=$this->data[1]['number_text']?></div>
	<div class="clear"></div>
</div>
<div class="num_text_block">
	<div class="item_header">Трактование числа достижений <?=$this->data[1]['number_text']?></div>
	<div class="text">
		<?=$this->data[1]['description']?>
		<div class="clear"></div>
	</div>
</div>

<div class="num_block">
	<img src="/files/images/profile/number/<?=$this->data[2]['number'].'.png';?>" alt="" />
	<div class="item_header">Третье число достижений <?=$this->data[2]['number_text']?></div>
	<div class="clear"></div>
</div>
<div class="num_text_block">
	<div class="item_header">Трактование числа достижений <?=$this->data[2]['number_text']?></div>
	<div class="text">
		<?=$this->data[2]['description']?>
		<div class="clear"></div>
	</div>
</div>

<div class="num_block">
	<img src="/files/images/profile/number/<?=$this->data[3]['number'].'.png';?>" alt="" />
	<div class="item_header">Четвертое число достижений <?=$this->data[3]['number_text']?></div>
	<div class="clear"></div>
</div>
<div class="num_text_block">
	<div class="item_header">Трактование числа достижений <?=$this->data[3]['number_text']?></div>
	<div class="text">
		<?=$this->data[3]['description']?>
		<div class="num_more"><a onclick="showForm()" style="cursor:pointer">Произвести другой нумерологический рассчет →</a></div>
		<div class="clear"></div>
	</div>
</div>