<div class="num_block">
	<img src="/files/images/profile/number/<?=$this->data['number'].'.png';?>" alt="" />
	<div class="item_header" style="padding: 45px 0 0 0">Число вашей личности <?=$this->data['number_text']?></div>
	<div class="clear"></div>
</div>
<div class="num_text_block">
	<div class="item_header">Трактование числа <?=$this->data['number_text']?></div>
	<div class="text">
		<?=$this->data['description']?>
		<div class="num_more"><a onclick="showForm()" style="cursor:pointer">Произвести другой нумерологический рассчет →</a></div>
		<div class="clear"></div>
	</div>
</div>