<script type="text/javascript">
    <!--
    function confirmation(id,page){
        if(confirm('Вы действительно хотите удалить эту опцию?')){
            window.location.href="/admin/poll/remove-option/id/" + id + '/page/' + page;
        }
    }
    //-->
</script>
<h1>Управление опциями голосования "<?=$this->poll['name']?>"</h1>
<table style="width: 100%">
    <tr>
        <td>
            <div style="text-align:left;"><a href="/admin/poll/add-option/id/<?=$this->poll['id']?>">Добавить опцию.</a></div>
        </td>
        <td>
            <div style="text-align:right;"><a href="/admin/poll/">Вернуться к голосованиям.</a></div>
        </td>
    </tr>
</table>
<table class="admin-table" id="article-table" style="width: 950px;margin-left: 30px;">
    <tr>
        <th style="width:60%">
            Название
        </th>
        <th style="width:20%">
            Действия
        </th>
    </tr>
    <?php if(count($this->data)):?>
        <?php foreach($this->data as $item):?>
            <tr>
                <td>
                    <a href="/admin/poll/edit-option/id/<?=$this->poll['id'] . '/option_id/' . $item['id'];?>"><?=$item['name'];?></a>
                </td>
                <td>
                    <a href="/admin/poll/edit-option/id/<?=$this->poll['id'] . '/option_id/' . $item['id'];?>">Редактировать</a> /
                    <a style="cursor:pointer;" onclick="confirmation('<?=$item['id']?>','')">Удалить</a>
                </td>
            </tr>
        <?php endforeach;?>
    <?php endif;?>
</table>