<form action="<?=$this->escape($this->element->getAction());?>" 
		method="<?=$this->escape($this->element->getMethod()); ?>"
		enctype="<?=$this->element->getEncType(); ?>"
		class="article-form">
	<table>
		<?=$this->element->title;?>
		<?=$this->element->type;?>
		<?=$this->element->back_note;?>
		<?=$this->element->back;?>
		<?=$this->element->reshuffle_note;?>
		<?=$this->element->reshuffle;?>
		<?=$this->element->removal_note;?>
		<?=$this->element->removal;?>
		<tr>
			<td colspan="2">
				<?=$this->element->page;?>
			</td>
		</tr>
		<tr>
			<td colspan="2" style="text-align:right">
				<?=$this->element->submit;?>
				<?=$this->element->cancel;?>
			</td>
		</tr>
	</table>
</form>