<form action="<?=$this->escape($this->element->getAction());?>" 
		method="<?=$this->escape($this->element->getMethod()); ?>"
		enctype="<?=$this->element->getEncType(); ?>"
		>
	<table>
		<?=$this->element->normal_note;?>
		<?=$this->element->normal;?>
		<?=$this->element->reverse_note;?>
		<?=$this->element->reverse;?>
		<tr>
			<td colspan="2" style="text-align:right">
				<?=$this->element->id;?>
				<?=$this->element->number;?>
				<?=$this->element->submit;?>
			</td>
		</tr>
	</table>
</form>