<form action="<?=$this->escape($this->element->getAction());?>" 
		method="<?=$this->escape($this->element->getMethod()); ?>"
		enctype="<?=$this->element->getEncType(); ?>" 
		class="article-form" >
	<table style="width: 980px">
		<?=$this->element->sign;?>
		<?=$this->element->description;?>
		<tr>
			<td colspan="2">
			<?=$this->element->page;?>
			</td>
		</tr>
		<tr>
			<td colspan="2" style="text-align:right">
				<?=$this->element->submit;?>
				<?=$this->element->cancel;?>
			</td>
		</tr>
	</table>
</form>
<script>
CKEDITOR.replace( 'description',{
	filebrowserBrowseUrl : '/js/ckfinder/ckfinder.html',
	filebrowserImageBrowseUrl : '/js/ckfinder/ckfinder.html?type=Images',
	filebrowserFlashBrowseUrl : '/js/ckfinder/ckfinder.html?type=Flash',
	filebrowserUploadUrl : '/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
	filebrowserImageUploadUrl : '/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
	filebrowserFlashUploadUrl : '/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'
} );
</script>