<form action="<?=$this->escape($this->element->getAction());?>" 
		method="<?=$this->escape($this->element->getMethod()); ?>"
		enctype="<?=$this->element->getEncType(); ?>"
		class="article-form">
	<table>
		<?=$this->element->startdate;?>
		<?=$this->element->enddate;?>
		<?=$this->element->is_retrograd;?>
		<?=$this->element->sign;?>
		<?=$this->element->desc;?>
		<tr>
			<td colspan="2">
			<?=$this->element->page;?>
			</td>
		</tr>
		<tr>
			<td colspan="2" style="text-align:right">
				<?=$this->element->submit;?>
				<?=$this->element->cancel;?>
			</td>
		</tr>
	</table>
</form>