<form action="<?=$this->escape($this->element->getAction());?>" 
		method="<?=$this->escape($this->element->getMethod()); ?>"
		enctype="<?=$this->element->getEncType(); ?>" 
		class="article-form">
	<table>
		<?=$this->element->url;?>
		<?=$this->element->name_ru;?>
		<?=$this->element->title;?>
		<?=$this->element->seokeywords;?>
		<?=$this->element->seodescription;?>
		<?=$this->element->minidesc;?>
		<tr>
			<td colspan="2">
			<?=$this->element->page;?>
			</td>
		</tr>
		<tr>
			<td colspan="2" style="text-align:right">
				<?=$this->element->submit;?>
				<?=$this->element->cancel;?>
			</td>
		</tr>
	</table>
</form>