<div id="article_mini">
	<div class="article_mini_line">
		<div class="article_mini_block">
			<div class="article_mini_block_header">
				<a href="#">Астрология</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ученые разглядели загадочную розовую планету</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Самые талантливые дети рождаются под знаком</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ледники антарктиды снова замерзают, вобщем скоро будет
					холодно там</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ученые разглядели загадочную розовую планету</a>
			</div>
			<div class="all">
				<a href="#">Все материалы</a>
			</div>
		</div>
		<div class="article_mini_block" id="mini_block_center">
			<div class="article_mini_block_header">
				<a href="#">Космос</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ученые разглядели загадочную розовую планету</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Самые талантливые дети рождаются под знаком</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ледники антарктиды снова замерзают, вобщем скоро будет
					холодно там</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ученые разглядели загадочную розовую планету</a>
			</div>
			<div class="all">
				<a href="#">Все материалы</a>
			</div>
		</div>
		<div class="article_mini_block">
			<div class="article_mini_block_header">
				<a href="#">Отношения</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ученые разглядели загадочную розовую планету</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Самые талантливые дети рождаются под знаком</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ледники антарктиды снова замерзают, вобщем скоро будет
					холодно там</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ученые разглядели загадочную розовую планету</a>
			</div>
			<div class="all">
				<a href="#">Все материалы</a>
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<div class="article_mini_line">
		<div class="article_mini_block">
			<div class="article_mini_block_header">
				<a href="#">Деньги</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ученые разглядели загадочную розовую планету</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Самые талантливые дети рождаются под знаком</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ледники антарктиды снова замерзают, вобщем скоро будет
					холодно там</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ученые разглядели загадочную розовую планету</a>
			</div>
			<div class="all">
				<a href="#">Все материалы</a>
			</div>
		</div>
		<div class="article_mini_block" id="mini_block_center2">
			<div class="article_mini_block_header">
				<a href="#">Мир</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ученые разглядели загадочную розовую планету</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Самые талантливые дети рождаются под знаком</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ледники антарктиды снова замерзают, вобщем скоро будет
					холодно там</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ученые разглядели загадочную розовую планету</a>
			</div>
			<div class="all">
				<a href="#">Все материалы</a>
			</div>
		</div>
		<div class="article_mini_block">
			<div class="article_mini_block_header">
				<a href="#">Стихийные бедствия</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ученые разглядели загадочную розовую планету</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Самые талантливые дети рождаются под знаком</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ледники антарктиды снова замерзают, вобщем скоро будет
					холодно там</a>
			</div>
			<div class="article_mini_item">
				<a href="#">Ученые разглядели загадочную розовую планету</a>
			</div>
			<div class="all">
				<a href="#">Все материалы</a>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>