<?php if (($this->pageCount) > 1){?>
	<div style="float: right;">
		<ul class="pager">
			<!-- First page link -->
			<?php if (isset($this->previous)): ?>
			  <li><a href="<?= '/'.$this->type.'/tag/'.$this->tag['alias'].'/'.$this->first ?>">&lt;&lt;</a></li>
			<?php else: ?>
			  <li><a href="#">&lt;&lt;</a></li>
			<?php endif; ?>
			<!-- Previous page link -->
			<?php if (isset($this->previous)): ?>
			  <li><a href="<?= '/'.$this->type.'/tag/'.$this->tag['alias'].'/'.$this->previous ?>">&lt;</a></li>
			<?php else: ?>
			  <li><a href="#">&lt;</a></li>
			<?php endif; ?>
			<!-- Numbered page links -->
			<?php foreach ($this->pagesInRange as $page): ?>
			  <?php if ($page != $this->current): ?>
				 <li><a href="<?='/'.$this->type.'/tag/'.$this->tag['alias'].'/'.$page; ?>"><?= $page; ?></a></li>
			  <?php else: ?>
			     <li><a href="#" class="selected"><?= $page; ?></a></li>
			  <?php endif; ?>
			<?php endforeach; ?>
			<!-- Next page link -->
			<?php if (isset($this->next)): ?>
			  <li><a href="<?= '/'.$this->type.'/tag/'.$this->tag['alias'].'/'.$this->next; ?>">&gt;</a></li>
			<?php else: ?>
			  <li><a href="#">&gt;</a></li>
			<?php endif; ?>
			<!-- Last page link -->
			<?php if (isset($this->next)): ?>
			  <li><a href="<?= '/'.$this->type.'/tag/'.$this->tag['alias'].'/'. $this->last; ?>">&gt;&gt;</a></li>
			<?php else: ?>
			  <li><a href="#">&gt;&gt;</a></li>
			<?php endif; ?>
		</ul>
	</div>
	<div style="clear: both;"></div>
<?php } ?>