<script type="text/javascript">
<!--
$(document).ready(function(){
	$('#seacrh-button').click(function(){
		$.post('/admin/news/search',
				{'query':$('#query').val()},
				function(data){
					$('#article-table').html(data);
				}
			);
		return false;
	});
});
function confirmation(id,page){
	if(confirm('Вы действительно хотите удалить эту статью?')){
		window.location.href="/admin/news/remove/id/" + id + '/page/' + page;
	}
}
//-->
</script>
<h1>Управление новостями</h1>
<table>
	<tr>
		<td>
			<div style="text-align:left;"><a href="/admin/news/add">Добавить новость.</a></div>
		</td>
		<td>
			<input id="query" type="text"/><input id="seacrh-button" type="button" value="Найти новость"/>
			<input type="button" id="clear-search" value="Очистить поиск" onclick='window.location.href="/admin/news"'/>
		</td>
	</tr>
</table>
<table class="admin-table" id="article-table" style="width:950px;margin-left: 30px;">
	<tr>
		<th style="width:60%">
			Заголовок
		</th>
		<th style="width:20%">
			Активность
		</th>
		<th style="width:20%">
			Действия
		</th>
	</tr>
	<?php if(count($this->paginator)):?>
	<?php foreach($this->paginator as $item):?>
	<tr>
		<td>
			<a href="/admin/news/edit/id/<?=$item['id']?><?=(!empty($this->page)?'/page/'.$this->page:'');?>"><?=$item['title'];?></a>
		</td>
		<td>
			<?=($item['activity'] == 'y')?'Активна':'Неактивна';?>
		</td>
		<td>
			<a href="/admin/news/edit/id/<?=$item['id']?><?=(!empty($this->page)?'/page/'.$this->page:'');?>">Редактировать</a> / 
			<a style="cursor:pointer;" onclick="confirmation('<?=$item['id']?>','<?=(!empty($this->page)?$this->page: (''))?>')">Удалить</a>
		</td>
	</tr>
	<?php endforeach;?>
	<tr>
		<td colspan="2">
			<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml',array('requestQuery' => $this->requestQuery, 'requestQueryArray' => $this->requestQueryArray, 'funcName' => 'changeAgentListPage')) ?>
		</td>
	</tr>
	<?php endif;?>
</table>