<script type="text/javascript">
<!--
	$(document).ready(function(){
		loadDay();
		$('#byear,#bmonth').change(function(){
			loadDay();
		});
		$('#submit').click(function(){
			
			var year = $('#byear option:selected').val();
			var month = $('#bmonth option:selected').val();
			var day = $('#bday option:selected').val();
			var error = 'false';
			if(year == '' ){
				alert('Не выбран год');
				error = 'true';
			}
			if(month == '' ){
				alert('Не выбран месяц');
				error = 'true';
			}
			if(day == '' ){
				alert('Не выбран день');
				error = 'true';
			}
			if(error == 'false'){
				$.post('/horoscope/get-karma-description',
					{
						'byear'		: year,
						'bmonth'	: month,
						'bday'		: day
					},
					function(data){
						var html = data.description;
						$('#description_wrapper').html(html);
						//console.log(data.description);
				},'json');
			}
			return false;
		});
		
		function loadDay(){
			if($('#byear option:selected').val() != '' && $('#bmonth option:selected').val() != ''){
				$.post(
						'/user/days',
						{
							'year' : $('#byear option:selected').val(),
						 	'month': $('#bmonth option:selected').val()
						 },
						 function(data){
							var html = '';
							for(var i in data){
								html += '<option vallue="'+i+'">' + data[i] + '</option>';
							}
							$('#bday').html(html);
						},
						'json');
			}
		}
	});
//-->
</script>
<h1>Кармичекий гороскоп</h1>
<?=$this->form?>
<div id="description_wrapper">
	
</div>