<script type="text/javascript">
<!--
	$(document).ready(function(){
		$('#check').click(function(){
			var manSign = $('#man_sign option:selected').val();
			var womanSign = $('#woman_sign option:selected').val();
			if(manSign != '' && womanSign != ''){
				$.post(
					'/horoscope/get-compability',
					{
						'sign1': $('#man_sign option:selected').val(),
						'sign2': $('#woman_sign option:selected').val(),
						'type': 'business',
						},
					function(data){
							var attributes = '<div style="width:400px;">';
							for(var i in data.attributes){
								for(var j in data.attribute_values){
									if(data.attributes[i]['id'] == data.attribute_values[j]['compability_attribute_id']){
										attributes += '<div style="width:180px;border:1px solid grey;float:left;">';
										attributes += data.attributes[i]['name_ru']+': '+data.attribute_values[j]['value'];
										attributes += '</div>';
									}
								}
							}
							attributes += '</div><div style="clear:both"></div>';
							$('#attributes').html(attributes);
							$('#compability').html(data.description);
							$('#sign1').text($('#man_sign option:selected').text());
							$('#sign2').text($('#woman_sign option:selected').text());
							$('#result-wrapper').show();
							$('#love-form').hide();
					},'json');
			}
		});
		
	});
	function restart(){
		$('#result-wrapper').hide();
		$('#love-form').show();
	}
//-->
</script>
<h1>Партнерская совместимость знака <?=$this->sign['sign_ru']?> с другими знаками</h1>
<div id="type-description">
	здесь описание совместимости и прочее бла бла бла
</div>
<form id="love-form">
	<table>
		<tr>
			<td>
				<img src=""/>
			</td>
			<td>
				<table>
					<tr>
						<td>
							Вы
						</td>
					</tr>
					<tr>
						<td>
							<select id="man_sign">
								<option value=""></option>
								<?php foreach($this->signs as $sign):?>
									<option value="<?=$sign['id']?>"
										<?=(isset($this->sign) && $this->sign['sign'] == $sign['sign'])?'selected="selected"':''?>>
										<?=$sign['sign_ru']?>
									</option>
								<?php endforeach;?>
							</select>
						</td>
					</tr>
				</table>
			</td>
			<td>
				<img src=""/> 
			</td>
			<td>
				<table>
					<tr>
						<td>
							Партнер
						</td>
					</tr>
					<tr>
						<td>
							<select id="woman_sign">
								<option value=""></option>
								<?php foreach($this->signs as $sign):?>
									<option value="<?=$sign['id']?>">
										<?=$sign['sign_ru']?>
									</option>
								<?php endforeach;?>
							</select>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan="4" style="text-align:right">
				<input id="check" type="button" value="Проверить"/>
			</td>
		</tr>
	</table>
</form>
<div id="result-wrapper" style="display:none;">
	<h2>Совместимость</h2>
	<table>
		<tr>
			<td>
				Знак
				<span id="sign1"></span>
			</td>
			<td>
				Знак
				<span id="sign2"></span>
			</td>
		</tr>
		<tr>
			<td>
				Вы
			</td>
			<td>
				Партнер
			</td>
		</tr>
	</table>
	<div id="attributes">
		
	</div>
	<div id="compability">
		
	</div>
	<a style="cursor:pointer" onclick="restart()">Проверить другую совместимость</a>
</div>

