<div>
	<table>
		<tr>
			<td style="vertical-align: top;">
				<img src="/files/images/test-taro.jpg"/>
			</td>
			<td>
				<table>
					<tr>
						<td>
							<h2><a href="/gadaniya/rune/<?=$this->parentAlias?>/<?=$this->item['alias']?>"><?=$this->item['name']?></a></h2>
						</td>
					</tr>
					<tr>
						<td>
							<?=$this->item['description']?>
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
</div>