<script type="text/javascript">
<!--
var divinationId = '<?=$this->divination['id']?>';

function cellDescription(cellOrder){
	$.post(
			'/divination/get-other-description',
			{
				'divination_id': divinationId,
				'order': cellOrder,
			},
			function(data){
				$('#our-alignment').show();
				$('#desc_wrapper_0').html(data);
				 $('html, body').animate({
				        scrollTop: $("#desc_wrapper_0").offset().top
				    }, 2000);
			}
		);
}
//-->
</script>
<div id="part2" style="width:970px;height:600px;border: 1px solid grey;">
	<div id="net" style="width:700px;border:1px solid black;height:598px;float:left;">
		<?php for($i=0;$i<100;$i++):?>
			<div class="divination-other-item" onclick="cellDescription('<?=$i+1?>');">
			</div>
		<?php endfor;?>
	</div>
	<div id="desc" style="width:165px;border:1px solid black;height:598px;float:left;">
		<p id="count-text" style="">Выберите ячейку</p>
	</div>
</div>
