<table class="admin-table" id="tags-table" style="width: 500px;margin-left: 30px;">
	<tr>
		<th style="width:80%">
			Тег
		</th>
		<th style="width:20%">
			Действия
		</th>
	</tr>
	<?php if(count($this->data)):?>
	<?php foreach($this->data as $item):?>
	<tr>
		<td>
			<?=$item['tagname'];?>
		</td>
		<td>
			<a href="/admin/newstag/edit/id/<?=$item['id']?>">Редактировать</a> / 
			<a style="cursor:pointer;" onclick="confirmation('<?=$item['id']?>','')">Удалить</a>
		</td>
	</tr>
	<?php endforeach;?>
	<?php endif;?>
</table>