<script type="text/javascript">
<!--
$(document).ready(function(){
	$('#seacrh-button').click(function(){
		$.post('/admin/users/search',
				{'query':$('#query').val()},
				function(data){
					$('#article-table').html(data);
				}
			);
	});
});
function changeActivity(id){
	$.post(
			'/admin/users/change-activity',
			{
				'id':id
			},
			function(data){
				if(data.errors.length != 0){
					var html = '<ul>';
					for(var i in data.errors){
						html += '<li>' + data.errors[i]+'</li>'; 
					}
					html = '</ul>';
					alert(html);
				}else{
					if($('#activity_' + id).text() == 'Акт'){
						$('#activity_' + id).text('Неакт');
					}else{
						$('#activity_' + id).text('Акт');
					}
				}
			},	
	'json');
	return false;
}
//-->
</script>
<h1>Управление пользователями</h1>
<table>
	<tr>
		<td>
			&nbsp;&nbsp;&nbsp;
		</td>
		<td>
			<input id="query" type="text"/><input id="seacrh-button" type="button" value="Найти пользователя"/>
			<input type="button" id="clear-search" value="Очистить поиск" onclick='window.location.href="/admin/users"'/>
		</td>
	</tr>
</table>
<div>
	Количество пользователей: <?=$this->usersCount?>
</div>
<table class="admin-table" id="article-table" style="width:950px;margin-left: 30px;">
	<tr>
		<th style="width:30%">
			ФИО
		</th>
		<th style="width:30%">
			Почта
		</th>
		<th style="width:20%">
			Дата рег-ции
		</th>
		<th style="width:20%">
			Посл.вход
		</th>
		<th style="width:5%">
			Акт.
		</th>
	</tr>
	<?php if(count($this->paginator)):?>
	<?php foreach($this->paginator as $item):?>
	<tr>
		<td>
			<?=$item['fullname']?>
		</td>
		<td>
			<?=$item['email']?>
		</td>
		<td>
			<?=$item['register_date']?>
		</td>
		<td>
			<?=$item['last_login']?>
		</td>
		<td>
			<a id="activity_<?=$item['id']?>" style="cursor:pointer" onclick="changeActivity('<?=$item['id']?>')"><?=($item['activity'] == 'y')?'Акт':'Неакт';?></a>
		</td>
	</tr>
	<?php endforeach;?>
	<tr>
		<td colspan="2">
			<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml',array('requestQuery' => $this->requestQuery, 'requestQueryArray' => $this->requestQueryArray, 'funcName' => 'changeAgentListPage')) ?>
		</td>
	</tr>
	<?php endif;?>
</table>