<div id="orange_sign">
	<div class="orange_sign_item4" 
		<?=($this->curType == 'personal')?'id="you_here"':''?>>
		<?php if($this->curType == 'personal'):?>
			Мои числа
		<?php else:?>
			<a href="/numerology/personal">Мои числа</a>
		<?php endif;?>
	</div>
	<div class="orange_sign_item4"
		<?=($this->curType == 'forecast')?'id="you_here"':''?>>
		<?php if($this->curType == 'forecast'):?>
			Мои прогнозы
		<?php else:?>
			<a href="/numerology/forecast">Прогнозы</a>
		<?php endif;?>
	</div>
	<div class="orange_sign_item4"
		<?=($this->curType == 'compability')?'id="you_here"':''?>>
		<?php if($this->curType == 'compability'):?>
			Совместимость
		<?php else:?>
			<a href="/numerology/compability">Совместимость</a>
		<?php endif;?>
	</div>
	<div class="clear"></div>
</div>