<form action="<?=$this->escape($this->element->getAction());?>" 
		method="<?=$this->escape($this->element->getMethod()); ?>"
		enctype="<?=$this->element->getEncType(); ?>" 
		class="article-form">
	<table>
		<?=$this->element->email;?>
		<?=$this->element->pass;?>
		<?=$this->element->pass_confirm;?>
		<?=$this->element->birthday;?>
		<tr>
			<td colspan="2">
				<img id="simple-refresh" src="/files/images/refresh.jpg" style="width:15px;cursor:pointer" title="Обновить"/>
				<?=$this->element->captcha?>
			</td>
		</tr>
		<tr>
			<td colspan="2" style="text-align:right">
				<?=$this->element->formtype;?>
				<?=$this->element->submit;?>
			</td>
		</tr>
	</table>
</form>