<div id="footer">
    <div id="up"></div>
    <div id="footer_wrap">
        <div id="footer_line1">
            <div id="footer_logo"></div>
            <div id="footer_links">
                <a href="/statyi/content/17-no-tag/46-o-proekte">О проекте</a>
                <a href="/statyi/content/17-no-tag/47-reklama-na-sayte">Реклама</a>
                <a id="footer-feedback" href="javascript:void(0)">Техподдержка</a>
            </div>
            <div id="counters">
            	<!-- begin of Top100 code -->
				<script id="top100Counter" type="text/javascript" src="http://counter.rambler.ru/top100.jcn?3021974"></script>
				<noscript>
					<a href="http://top100.rambler.ru/navi/3021974/">
						<img src="http://counter.rambler.ru/top100.cnt?3021974" alt="Rambler's Top100" border="0" />
					</a>
				
				</noscript>
				<!-- end of Top100 code -->
            </div>
            <div class="clear"></div>
        </div>
        <div id="footer_line2">
            <div id="footer_subscribe">
                <span id="footer_sub1">подписаться</span>
                <a target="_blank" href="https://www.facebook.com/groups/628871420540971/"><img src="/files/images/facebook.png" alt=""></a>
                <a target="_blank" href="https://vk.com/club71399535"><img src="/files/images/vk.png" alt=""></a>
				<a target="_blank" href="https://twitter.com/Astro_Tarot_ru"><img src="/files/images/twitter.png" alt=""></a>
            </div>
            <div id="ochepyatka"></div>
            <div id="copyright">© <?=date('Y')?> "AstroTarot". Дизайн сайта - <a href="http://www.studio23.com.ua/">Design 23</a></div>
        </div>
    </div>
</div>