<div id="right_hrskp">
	<div class="actual_header">Гороскопы</div>
	<div class="hrskp_item">
		<img src="/files/images/sign_small1.png" alt="" />
		<div class="item_header"><a href="/horoscope/aries/today"><span>Овен</span><br />21.03-20.04</a></div>
	</div>
	<div class="hrskp_item">
		<img src="/files/images/sign_small2.png" alt="" />
		<div class="item_header"><a href="/horoscope/taurus/today"><span>Телец</span><br />21.04-20.05</a></div>
	</div>
	<div class="clear"></div>
	<div class="hrskp_item">
		<img src="/files/images/sign_small3.png" alt="" />
		<div class="item_header"><a href="/horoscope/gemini/today"><span>Близнецы</span><br />21.05-21.06</a></div>
	</div>
	<div class="hrskp_item">
		<img src="/files/images/sign_small4.png" alt="" />
		<div class="item_header"><a href="/horoscope/cancer/today"><span>Рак</span><br />22.06-22.07</a></div>
	</div>
	<div class="clear"></div>
	<div class="hrskp_item">
		<img src="/files/images/sign_small5.png" alt="" />
		<div class="item_header"><a href="/horoscope/leo/today"><span>Лев</span><br />23.07-23.08</a></div>
	</div>
	<div class="hrskp_item">
		<img src="/files/images/sign_small6.png" alt="" />
		<div class="item_header"><a href="/horoscope/virgo/today"><span>Дева</span><br />24.08-23.09</a></div>
	</div>
	<div class="clear"></div>
	<div class="hrskp_item">
		<img src="/files/images/sign_small7.png" alt="" />
		<div class="item_header"><a href="/horoscope/libra/today"><span>Весы</span><br />24.09-23.10</a></div>
	</div>
	<div class="hrskp_item">
		<img src="/files/images/sign_small8.png" alt="" />
		<div class="item_header"><a href="/horoscope/scorpio/today"><span>Скорпион</span><br />24.10-22.11</a></div>
	</div>
	<div class="clear"></div>
	<div class="hrskp_item">
		<img src="/files/images/sign_small9.png" alt="" />
		<div class="item_header"><a href="/horoscope/sagittarius/today"><span>Стрелец</span><br />23.11-21.12</a></div>
	</div>
	<div class="hrskp_item">
		<img src="/files/images/sign_small10.png" alt="" />
		<div class="item_header"><a href="/horoscope/capricorn/today"><span>Козерог</span><br />22.12-20.01</a></div>
	</div>
	<div class="clear"></div>
	<div class="hrskp_item">
		<img src="/files/images/sign_small11.png" alt="" />
		<div class="item_header"><a href="/horoscope/aquarius/today"><span>Водолей</span><br />21.01-20.02</a></div>
	</div>
	<div class="hrskp_item">
		<img src="/files/images/sign_small12.png" alt="" />
		<div class="item_header"><a href="/horoscope/pisces/today"><span>Рыбы</span><br />21.02-20.03</a></div>
	</div>
	<div class="clear"></div>
	<div class="more"><a href="/horoscope">все гороскопы →</a></div>
</div>