<!-- 
<div class="soc_line">
	<div class="share">Поделиться</div>
	<div class="code"><a href="#"><img src="/files/images/facebook.png" alt="" /></a></div>
	<div class="how"><img src="/files/images/soc_corner.png" alt="" />12</div>
	<div class="code"><a href="#"><img src="/files/images/vk.png" alt="" /></a></div>
	<div class="how"><img src="/files/images/soc_corner.png" alt="" />150</div>
	<div class="code"><a href="#"><img src="/files/images/twitter.png" alt="" /></a></div>
	<div class="how"><img src="/files/images/soc_corner.png" alt="" />0</div>
	<div class="code"><a href="#"><img src="/files/images/plus.png" alt="" /></a></div>
</div>
 -->
<script type="text/javascript">(function() {
  if (window.pluso)if (typeof window.pluso.start == "function") return;
  if (window.ifpluso==undefined) { window.ifpluso = 1;
    var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
    s.type = 'text/javascript'; s.charset='UTF-8'; s.async = true;
    s.src = ('https:' == window.location.protocol ? 'https' : 'http')  + '://share.pluso.ru/pluso-like.js';
    var h=d[g]('body')[0];
    h.appendChild(s);
  }})();</script>

<div class="soc_line">  
	<div data-user="727286693" class="pluso" data-background="transparent" data-options="small,round,line,horizontal,nocounter,theme=04" data-services="vkontakte,facebook,twitter,email"></div>
</div>