<script type="text/javascript" src="/js/ckeditor/ckeditor.js"></script>
<?php if($this->actionType == 'add'):?>
    <h1>Добавление сонника</h1>
<?php elseif($this->actionType == 'edit'):?>
    <h1>Редактирование сонника</h1>
<?php endif; ?>
<?=$this->form;?>
<script type="text/javascript">
    <!--
    CKEDITOR.replace( 'description',	{
        filebrowserBrowseUrl : '/js/ckfinder/ckfinder.html',
        filebrowserImageBrowseUrl : '/js/ckfinder/ckfinder.html?type=Images',
        filebrowserFlashBrowseUrl : '/js/ckfinder/ckfinder.html?type=Flash',
        filebrowserUploadUrl : '/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
        filebrowserImageUploadUrl : '/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
        filebrowserFlashUploadUrl : '/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'
    } );
    //-->
</script>