<script type="text/javascript">
<!--
function confirmation(id,page){
	if(confirm('Вы действительно хотите удалить эту страницу?')){
		window.location.href="/admin/dream/remove-page/id/" + id + '/page/' + page;
	}
}
//-->
</script>
<h1>SEO настройки и миниописания сонника</h1>
<table>
	<tr>
		<td>
			<div style="text-align:left;"><a href="/admin/dream/add-page">Добавить страницу.</a></div>
		</td>
	</tr>
</table>
<table class="admin-table" id="article-table" style="width:950px;margin-left: 30px;">
	<tr>
		<th style="width:80%">
			Заголовок
		</th>
		<th style="width:20%">
			Действия
		</th>
	</tr>
	<?php if(count($this->paginator)):?>
	<?php foreach($this->paginator as $item):?>
	<tr>
		<td>
			<a href="/admin/dream/edit-page/id/<?=$item['id']?><?=(!empty($this->page)?'/page/'.$this->page:'');?>"><?=$item['name_ru'];?></a>
		</td>
		<td>
			<a href="/admin/dream/edit-page/id/<?=$item['id']?><?=(!empty($this->page)?'/page/'.$this->page:'');?>">Редактировать</a> /
			<a style="cursor:pointer;" onclick="confirmation('<?=$item['id']?>','<?=(!empty($this->page)?$this->page: (''))?>')">Удалить</a>
		</td>
	</tr>
	<?php endforeach;?>
	<tr>
		<td colspan="2">
			<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml',array('requestQuery' => $this->requestQuery, 'requestQueryArray' => $this->requestQueryArray, 'funcName' => 'changeAgentListPage')) ?>
		</td>
	</tr>
	<?php endif;?>
</table>