<table class="admin-table" id="article-table" style="width: 950px;margin-left: 30px;">
    <tr>
        <th style="width:80%">
            Слово
        </th>
        <th style="width:20%">
            Действия
        </th>
    </tr>
    <?php if(count($this->data)):?>
        <?php foreach($this->data as $item):?>
            <tr>
                <td>
                    <a href="/admin/dream/edit-word/id/<?=$item['id']?><?=(!empty($this->page)?'/page/'.$this->page:'');?>"><?=$item['word'];?></a>
                </td>
                <td>
                    <a href="/admin/dream/edit-word/id/<?=$item['id']?><?=(!empty($this->page)?'/page/'.$this->page:'');?>">Редактировать</a> /
                    <a style="cursor:pointer;" onclick="confirmation('<?=$item['id']?>','<?=(!empty($this->page)?$this->page: (''))?>')">Удалить</a>
                </td>
            </tr>
        <?php endforeach;?>
    <?php endif;?>
</table>