<script type="text/javascript">
    <!--
    $(document).ready(function(){
        $('#seacrh-button').click(function(){
            $.post('/admin/dream/search-word',
                {'query':$('#query').val()},
                function(data){
                    $('#article-table').html(data);
                }
            );
        });
    });
    function confirmation(id,page){
        if(confirm('Вы действительно хотите удалить это слово?')){
            window.location.href="/admin/dream/remove-word/id/" + id + '/page/' + page;
        }
    }
    //-->
</script>
<h1>Управление словами сонника</h1>
<table>
    <tr>
        <td>
            <div style="text-align:left;"><a href="/admin/dream/add-word">Добавить слово.</a></div>
        </td>
        <td>
            <input id="query" type="text"/><input id="seacrh-button" type="button" value="Найти слово"/>
            <input type="button" id="clear-search" value="Очистить поиск" onclick='window.location.href="/admin/dream/list-word"'/>
        </td>
    </tr>
</table>
<table class="admin-table" id="article-table" style="width: 950px;margin-left: 30px;">
    <tr>
        <th style="width:80%">
            Слово
        </th>
        <th style="width:20%">
            Действия
        </th>
    </tr>
    <?php if(count($this->paginator)):?>
        <?php foreach($this->paginator as $item):?>
            <tr>
                <td>
                    <a href="/admin/dream/edit-word/id/<?=$item['id']?><?=(!empty($this->page)?'/page/'.$this->page:'');?>"><?=$item['word'];?></a>
                </td>
                <td>
                    <a href="/admin/dream/edit-word/id/<?=$item['id']?><?=(!empty($this->page)?'/page/'.$this->page:'');?>">Редактировать</a> /
                    <a style="cursor:pointer;" onclick="confirmation('<?=$item['id']?>','<?=(!empty($this->page)?$this->page: (''))?>')">Удалить</a>
                </td>
            </tr>
        <?php endforeach;?>
        <tr>
            <td colspan="2">
                <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml',array('requestQuery' => $this->requestQuery, 'requestQueryArray' => $this->requestQueryArray, 'funcName' => 'changeAgentListPage')) ?>
            </td>
        </tr>
    <?php endif;?>
</table>