<?php if (($this->pageCount) > 1):?>
	<div id="pagination">
		<?php if (isset($this->previous)): ?>
			<div class="page_item_big" onclick="document.location.href='<?= '/'.$this->type.'/tag/'.$this->tag['alias'].'/'.$this->previous ?>'">
				<a href="<?= '/'.$this->type.'/tag/'.$this->tag['alias'].'/'.$this->previous ?>">← Предыдущая</a>
			</div>
		<?php endif;?>
		<?php foreach ($this->pagesInRange as $page): ?>
			<?php if ($page != $this->current): ?>
				 <div class="page_item" onclick="document.location.href='<?='/'.$this->type.'/tag/'.$this->tag['alias'].'/'.$page; ?>'">
				 	<a href="<?='/'.$this->type.'/tag/'.$this->tag['alias'].'/'.$page; ?>"><?= $page; ?></a>
				 </div>
			  <?php else: ?>
			     <div class="page_item" style="background-color:#ff6a00; color:#fff;"><?=$page;?></div>
			  <?php endif; ?>
		<?php endforeach;?>
		<?php if (isset($this->next)): ?>
		  <div class="page_item_big" onclick="document.location.href='<?= '/'.$this->type.'/tag/'.$this->tag['alias'].'/'.$this->next; ?>'">
		  	<a href="<?= '/'.$this->type.'/tag/'.$this->tag['alias'].'/'.$this->next; ?>">Следующая →</a>
		  </div>
		<?php endif; ?>
	</div>
<?php endif;?>

