<?php
$this->headScript()->appendFile(
				'/js/plugins/jquery.form.min.js',
				'text/javascript')
			->appendFile(
				'/js/scripts/profile.js',
				'text/javascript');
?>
<div class="left-column">
	<ul>
		<li>
			<a href="/profile">Мой кабинет</a>
		</li>
		<li>
			<a href="/profile/edit">Настроить профиль</a>
		</li>
		<li>
			<a href="#">Мои избранные гадания</a>
		</li>
		<li>
			<a href="#">Гороскоп на сегодня</a>
		</li>
		<li>
			<a href="#">Карта Таро дня</a>
		</li>
		<li>
			<a href="#">Руна дня</a>
		</li>
		<li>
			<a href="#">Гексаграмма дня</a>
		</li>
		<li>
			<a href="#">Число дня</a>
		</li>
	</ul>
</div>
<div class="main-content">
	<div class="content-header" style="border: 1px solid grey;">
		
	</div>
	<div id="loading" style="border:1px solid green;display:none;">
		<table>
			<tr>
				<td style="width:10%">
					<img src="/files/images/progress_small.gif"/>
				</td>
				<td style="width:90%">
					<span style="color:green;">Пожалуйста подождите, идет проверка введенных данных</span>
				</td>
			</tr>
		</table>
	</div>
	<div id="success" style="border: 1px solid green;display:none;">
		<span style="color:green;">Данные сохранены.</span>
	</div>
	<?=$this->form?>
</div>
<div class="right-column">
	<table>
		<tr>
			<td>
				<input type="button" onclick="window.location.href='/user/logout'" value="Выйти"/>
			</td>
		</tr>
		<tr>
			<td>
				<?=$this->avatar;?>
				<div id="message">
					<ul class="errors">
					</ul>
				</div>
			</td>
		</tr>
	</table>
	<div class="activity" style="border: 1px solid grey; margin-top: 20px;">
		<b>Активность</b>
		<table>
			<tr>
				<td>
					Регистрация
				</td>
			</tr>
			<tr>
				<td>
					<?php $date = new Zend_Date($this->userdata->register_date);
						echo $date->toString(Zend_Date::DATE_LONG);?>
				</td>
			</tr>
			<tr>
				<td>
					Последний вход
				</td>
			</tr>
			<tr>
				<td>
					<?php $date = new Zend_Date($this->userdata->last_login);
						echo $date->toString(Zend_Date::DATETIME);?>
				</td>
			</tr>
			<tr>
				<td>
					<a id="remove-profile" style="cursor:pointer;">Удалить мою учетную запись</a>
				</td>
			</tr>
		</table>
	</div>
</div>